#!/usr/bin/env bash

PROJECT_DIR="project"
CONTROL_FILE="$PROJECT_DIR/DEBIAN/control"
PACKAGE_KEY="Package: "
PACKAGE_ENTRY=$(grep "$PACKAGE_KEY" "$CONTROL_FILE")
PACKAGE=${PACKAGE_ENTRY//$PACKAGE_KEY}
VERSION_KEY="Version: "
VERSION_ENTRY=$(grep "$VERSION_KEY" "$CONTROL_FILE")
VERSION=${VERSION_ENTRY//$VERSION_KEY}

dpkg-deb --root-owner-group --build "$PROJECT_DIR" "$PACKAGE-$VERSION.deb"
